# Generated by Django 4.1.7 on 2023-03-30 09:50

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('product_title', models.CharField(max_length=200)),
                ('product_image1', models.ImageField(upload_to='')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_description', models.TextField()),
                ('product_price', models.IntegerField()),
                ('product_buying_cost', models.IntegerField()),
                ('product_address', models.TextField()),
                ('product_category', models.CharField(max_length=100)),
                ('is_create', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_city', models.CharField(max_length=150)),
                ('user_state', models.CharField(max_length=150)),
                ('user_pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_profile_pic', models.FileField(upload_to='')),
                ('user_name', models.CharField(max_length=100)),
                ('user_mobile_number', models.ImageField(upload_to='')),
            ],
        ),
    ]
