# Generated by Django 4.1.7 on 2023-03-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('className', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=4)),
                ('studentDetails', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
