# Generated by Django 4.1.7 on 2023-03-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_userfilesd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userfilesd',
        ),
        migrations.AddField(
            model_name='student',
            name='images',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
