# Generated by Django 4.1.7 on 2023-03-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_delete_userfilesd_student_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='images',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
