# Generated by Django 4.1.7 on 2023-03-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_student_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='images',
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
