# Generated by Django 4.1.7 on 2023-04-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='Product_image/')),
                ('filedFiled', models.FileField(upload_to='file/')),
            ],
        ),
    ]
