# Generated by Django 4.1.7 on 2023-04-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagestesting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_images',
            name='filedFiled',
        ),
        migrations.AlterField(
            model_name='product_images',
            name='images',
            field=models.ImageField(upload_to='Product_imag'),
        ),
    ]
